equirectangular_node:
  ros__parameters:
    cx_offset: 0.0
    cy_offset: 0.0
    front_cx_offset: 0.0
    front_cy_offset: -3.0
    back_cx_offset: 0.0
    back_cy_offset: 2.0
    crop_size: 1359
    translation: [0.005, 0.0, -0.01]
    rotation_deg: [0.0, 0.0, -0.5]
    gpu: False
    out_width: 1920
    out_height: 960
    target_fps: 15.0
    enable_seam_blending: False


equirectangular_cuda_node:
  ros__parameters:
    cx_offset: 0.0
    cy_offset: 0.0
    front_cx_offset: 0.0
    front_cy_offset: -3.0
    back_cx_offset: 0.0
    back_cy_offset: 2.0
    crop_size: 1359
    translation: [0.005, 0.0, -0.01]
    rotation_deg: [0.0, 0.0, -0.5]
    gpu: True
    out_width: 1920
    out_height: 960
    target_fps: 15.0
    enable_seam_blending: False

