equirectangular_node:
  ros__parameters:
    cx_offset: 0.0
    cy_offset: 0.0
    front_cx_offset: 0.0
    front_cy_offset: -5.0
    back_cx_offset: 0.0
    back_cy_offset: 12.0
    crop_size: 1405
    translation: [0.0, -0.018, -0.105]
    rotation_deg: [-0.5, 0.6, -0.4]
    gpu: True
    out_width: 1920
    out_height: 960
    target_fps: 15.0

